// ATLClient.idl : ATLClient 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLClient.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(02FBDC2D-8FAF-43A9-A40D-68F90B4220C8),
	version(1.0),
]
library ATLClientLib
{
	importlib("stdole2.tlb");
};

